package com.demo.Util;

public interface IRSValues {
    int RESOURCE_MANAGER = 101;
    int RMG_EXECUTIVE = 102;
    int ADMIN = 103;
    int INVALID_USER = 104;

    int ALLOCATED_IN_PROJECT = 201;
    int UNALLOCATED = 202;

    int REQUISISTION_REQUEST_OPEN = 300;
    int REQUISISTION_REQUEST_CLOSED = 301;

    int REQUISITION_SUGGESTION_ACCEPTED = 400;
    int REQUISITION_SUGGESTION_REJECTED = 401;
    int REQUISITION_SUGGESTION_SUGGESTED = 402;
}
